version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=pcsk_2Dx6LL_EfMidj71k7NaGA5QAcYfFgAGuqkBUZdCNdxymN4C1Hk8EEF7y7sRq7FhcoCcGHU
      - PINECONE_INDEX=${PINECONE_INDEX}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
